version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knative_demo
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db-init-scripts/postgres:/docker-entrypoint-initdb.d
volumes:
  postgres:
    driver: local