apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: my-connect-cluster
  name: postgres-addresses-debezium-connector
  namespace: <NAMESPACE>
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    plugin.name: pgoutput
    database.hostname: postgres.<NAMESPACE>.svc.cluster.local
    database.port: 5432
    database.user: postgres
    database.password: postgres
    database.dbname: knative_demo
    database.server.name: addresses-db
    schema.include.list: public
    table.include.list: public.addresses_changed
    database.history.kafka.topic: dbhistory.addresses
    database.history.kafka.bootstrap.servers: 'my-cluster-kafka-bootstrap.<NAMESPACE>.svc.cluster.local:9092'
    topic.prefix: addresseschanged
    slot.name: addresseschanged
  tasksMax: 1