kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-broker-channel
  namespace: 'maarten-playground'
data:
  channelTemplateSpec: |
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
      numPartitions: 3
      replicationFactor: 1
