apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: microservice-account-on-person-data-changed-subscription
  namespace: <NAMESPACE>
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: kafka-person-data-changed-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-service-microservice-account
      namespace: <NAMESPACE>