apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  name: my-connect-cluster
spec:
  bootstrapServers: knative-demo-cluster-kafka-bootstrap.maarten-playground.svc.cluster.local:9092
  build:
    output:
      image: quay.io/rh_ee_mvandepe/kafka-connect-cluster:latest
      pushSecret: rh-ee-mvandepe-test-pull-secret
      type: docker
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://a.plugin.url/debezium-connector-postgres-1.3.1.Final-plugin.tar.gz
            sha512sum: 962a12151bdf9a5a30627...f035a0447cb820077af00c03
      - name: camel-elasticsearch-rest-kafka-connector
        artifacts:
          - type: tgz
            url: https://a.plugin.url/camel-elasticsearch-rest-kafka-connector-0.10.0-package.tar.gz
  config:
    config.storage.topic: my-connect-cluster-configs
    offset.storage.topic: my-connect-cluster-offsets
    status.storage.topic: my-connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  replicas: 2
  version: 3.3.1