apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: <NAMESPACE>
  name: knative-serving-monolith
spec:
  template:
    spec:
      containers:
        - image: quay.io/appdev_playground/knative_demo:<VERSION>
          ports:
            - containerPort: 8080